### ISSUE TITLE
On which base you are classified the data.

### ISSUE THREAD

**Issue by zeeno95** [razor08/Efficient-CNN-BiLSTM-for-Network-IDS#6]
On which base you are classified the data. I'm not getting how to classify the data??

**Comment by jayxsinha** [comment]
In NSL-KDD, we are grouping up different attacks in a one-up category. This is a very common practice for NSL-KDD dataset, look it up! 
Reason: With 39 attacks types and normal, making it to 40, we don't have enough balanced data for each category, that's why one-up grouping is needed. 

Hope this helps.

**Comment by zeeno95** [comment]
what about the unsw-nb15 dataset on which base you are classified the data?
